apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-staging-manager
  namespace: {{ .Values.environment }}-environment
spec:
  selector:
    matchLabels:
      app: ingest-staging-manager
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-staging-manager
    spec:
      containers:
      - env:
        - name: INGEST_API
          value: http://$(INGEST_CORE_SERVICE_SERVICE_HOST):$(INGEST_CORE_SERVICE_SERVICE_PORT)
        - name: RABBIT_URL
          value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        - name: STAGING_API
          value: {{ .Values.uploadScheme}}://{{ .Values.upload }}
        - name: INGEST_API_KEY
          valueFrom:
            secretKeyRef:
              key: staging-api-key
              name: api-keys
        image: quay.io/humancellatlas/ingest-staging-manager:{{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-staging-manager
