# This is mostly to help dev team run the restore script locally for testing.
# This also helps to document the necessary configuration to run verification.
version: '3'
services:
  restore:
    build:
      dockerfile: Dockerfile-verify
      context: .
    image: quay.io/humancellatlas/ingest-backup-verify
    environment:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID 
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY 
    - AWS_ROLE_ARN=$AWS_ROLE_ARN 
    - S3_BUCKET=ingest-db-backup 
    - BACKUP_DIR=dev
    - MONGO_HOST=mongo
    - MONGO_USER=test
    - MONGO_PASSWORD=verify
    - SLACK_WEBHOOK=$SLACK_WEBHOOK
  mongo:
    image: mongo:4.2
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=test
    - MONGO_INITDB_ROOT_PASSWORD=verify
