# This is mostly to help dev team run the backup script locally for testing.
# This also helps to document the necessary configuration to run backup.
version: '3'
services:
  backup:
    build:
      dockerfile: Dockerfile-backup
      context: .
    image: quay.io/humancellatlas/ingest-backup
    environment:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID 
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY 
    - AWS_ROLE_ARN=$AWS_ROLE_ARN 
    - S3_BUCKET=ingest-db-backup 
    - BACKUP_DIR=dev
    - MONGO_HOST=mongo
  mongo:
    image: mongo:4.2
    ports:
    - "27017:27017"
