FROM quay.io/ebi-ait/ingest-kube-deployment:ingest-backup-base_20210929.1

RUN mkdir -p /data/db/dump

WORKDIR /opt
COPY src/backup.sh backup
COPY src/aws_setup .

RUN chmod +x backup

ENV S3_BUCKET=ingest-db-backup
ENV BACKUP_DIR=deploymentenv

CMD /opt/backup
