FROM quay.io/humancellatlas/ingest-backup-base:8ac6511

RUN mkdir -p /data/db/dump

WORKDIR /opt
COPY src/backup.sh backup
COPY src/aws_setup .

RUN chmod +x backup

ENV S3_BUCKET=ingest-backup
ENV BACKUP_DIR=deploymentenv

CMD /opt/backup
