FROM quay.io/ebi-ait/ingest-kube-deployment:ingest-backup-base_20210929.1

WORKDIR /opt
COPY src/aws_setup aws_setup
COPY src/restore.sh restore
COPY src/verify_backup .


RUN chmod +x ./restore;\
    chmod +x ./verify.py;\
    chmod +x ./log.py;\
    pip3 install -r requirements.txt

ENV MONGO_HOST=localhost
ENV MONGO_USER=user
ENV MONGO_PASSWORD=password
ENV SLACK_WEBHOOK=default

CMD ./restore
