aws:
  s3:
    bucket: ingest-db-backup
    directory: default
secret:
  aws:
    accessKey: default
    secretAccessKey: default
backup:
  image:
    repository: quay.io/humancellatlas/ingest-backup
    tag: cb2b26c
    pullPolicy: Always
  cronSchedule: 0 0 * * *
verification:
  image:
    repository: quay.io/humancellatlas/ingest-backup-verify
    tag: cb2b26c
    pullPolicy: Always
  mongo:
    image:
      repository: mongo
      tag: 3.4.3
      pullPolicy: Always
    auth:
      user: test
      password: verify
  cronSchedule: "*/1 * * * *"
  slack:
    webhookUrl: https://hooks.slack.com/services/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
