aws:
  roleArn: default
  s3:
    bucket: ingest-db-backup
    directory: default
secret:
  aws:
    accessKey: default
    secretAccessKey: default
backup:
  image:
    repository: quay.io/ebi-ait/ingest-kube-deployment
    tag: ingest-backup_20210929.1
    pullPolicy: Always
  cronSchedule: 0 0 * * *
verification:
  image:
    repository: quay.io/ebi-ait/ingest-kube-deployment
    tag: ingest-backup-verify_20210929.2
    pullPolicy: Always
  mongo:
    image:
      repository: mongo
      tag: 4.2
      pullPolicy: Always
    auth:
      user: test
      password: verify
  cronSchedule: 30 0 * * *
  slack:
    webhookUrl: default
