#!/bin/bash

secret=ingest/${DEPLOYMENT_STAGE}/secrets

function get_secret() {
    secret=$(aws --region us-east-1 secretsmanager get-secret-value\
                 --secret-id $secret\
                 --query SecretString\
                 --output text 2> /dev/null)
}

get_secret

staging_api_key=$(echo $secret | jq -r .staging_api_key | base64)
exporter_access_key_id=$(echo $secret | jq -r .ingest_exporter_access_key | base64)
exporter_access_key_secret=$(echo $secret | jq -r .ingest_exporter_access_secret | base64)
exporter_terra_auth_info=$(echo $secret | jq -r .ingest_exporter_terra_svc_account | base64)

source ../config/environment_$DEPLOYMENT_STAGE &&\
helm upgrade secrets secrets\
    --set environment=$DEPLOYMENT_STAGE\
    --set apiKeys.stagingApiKey=$staging_api_key\
    --set apiKeys.exporterAuthInfo=$exporter_auth_info\
    --set apiKeys.exporterTerraAuthInfo=$exporter_terra_auth_info\
    --set awsKeys.exporterAccessKeyId=$exporter_access_key_id\
    --set awsKeys.exporterAccessKeySecret=$exporter_access_key_secret\
    --force --install
