#!/bin/bash

secret=ingest/${DEPLOYMENT_STAGE}/secrets

function get_secret() {
    secret=$(aws --region us-east-1 secretsmanager get-secret-value\
                 --secret-id $secret\
                 --query SecretString\
                 --output text 2> /dev/null)
}

get_secret

staging_api_key=$(echo $secret | jq -r .staging_api_key | tr -d '\n' | base64)
exporter_auth_info=$(echo $secret | jq -r .exporter_auth_info | jq -r .private_key | tr -d '\n' | base64)

source ../config/environment_$DEPLOYMENT_STAGE &&\
helm upgrade secrets secrets\
    --set environment=$DEPLOYMENT_STAGE\
    --set apiKeys.stagingApiKey=$staging_api_key\
    --set apiKeys.exporterAuthInfo=$exporter_auth_info\
    --force --install
