#!/bin/bash

function get_secret() {
    secret_id=$1
    secret_field=$2
    aws --region us-east-1 secretsmanager get-secret-value\
	--secret-id ${secret_id}\
	--query SecretString --output text |\
	jq -r .${secret_field} |\
	tr -d '\n' |\
	base64
}

export staging_api_key=$(get_secret dcp/ingest/${DEPLOYMENT_STAGE}/secrets staging_api_key)
export exporter_auth_info=$(get_secret dcp/ingest/${DEPLOYMENT_STAGE}/secrets exporter_auth_info)
