apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.headless-service-name" . }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.port }}
      name: "solr-headless"
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
