apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: redis-service
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
