---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-archiver
  namespace: prod-environment
  labels:
    role: ingestion
spec:
  replicas: 3
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-archiver
    spec:
      containers:
         - name: ingest-archiver
           imagePullPolicy: Always
           image: quay.io/humancellatlas/ingest-archiver
           env:
             - name: INGEST_API
               value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
             - name: RABBITMQ_URL
               value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT}
             - name: RABBITMQ_ARCHIVAL_QUEUE
               value: ingest.archival.queue
             - name: RABBITMQ_SUBMITTED_EXCHANGE
               value: ingest.envelope.submitted.exchange
             - name: RABBITMQ_SUBMITTED_QUEUE
               value: ingest.envelope.submitted.queue
             - name: AAP_API_URL
               value: https://explore.api.aap.tsi.ebi.ac.uk/auth
             - name: AAP_API_DOMAIN
               value: self.hca-user
             - name: AAP_API_USER
               value: hcaingestd
             - name: USI_API_URL
               value: https://submission-dev.ebi.ac.uk
             - name: AAP_API_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: api-keys
                   key: aap-api-password
