---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbit
  namespace: prod-environment
  labels:
    role: submission
spec:
  replicas: 1 
  strategy: # we should have a rolling update strategy i.e changes deployed automatically
    type: "RollingUpdate"
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
         - name: rabbit
           image: rabbitmq:3-management-alpine
           ports:
             - containerPort: 5672
             - containerPort: 15672
