FROM quay.io/humancellatlas/ingest-backup-base:8ac6511

WORKDIR /opt
COPY src/aws_setup aws_setup
COPY src/restore.sh restore
COPY src/verify_backup .


RUN chmod +x ./restore;\
    chmod +x ./verify.py;\
    chmod +x ./log.py;\
    pip3 install -r requirements.txt

ENV MONGO_HOST=localhost
ENV MONGO_USER=user
ENV MONGO_PASSWORD=password
ENV SLACK_WEBHOOK=default

CMD ./restore
