apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: ingress
version: 0.1.0
dependencies:
    - name: ingress-nginx
      version: 3.23.0
      repository: https://kubernetes.github.io/ingress-nginx
