ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.staging.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.staging.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.staging.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: ui.ingest.staging.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:861229788715:certificate/437c38aa-c728-44a9-80a7-d13bb9babd98
