ingress:
  enabled: "false"

# for subchart ingress-nginx

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      targetPorts:
          https: http
  rbac:
    create: "true"
