ingress:
  enabled: "false"      

# for subchart ingress-nginx

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      targetPorts:
          https: http
    config:
      hsts: "true"
      server-tokens: "false"
      use-forwarded-headers: "true"
  rbac:
    create: "true"