variables:
  ENVIRONMENT_NAME: 
    value: "dev"
    description: "The environment to update the secret in"
    options:
      - "dev"
      - "staging" 
      - "prod"
  SECRET_VALUE: 
    description: "The value of the secret to update"
    value: ""
  INGEST_KUBE_DEPLOYMENT_REPO: "https://github.com/ebi-ait/ingest-kube-deployment.git"


stages:
  # rotate gcp secret, see https://github.com/ebi-ait/dcp-ingestcentral#dcp-1074
  - rotate_secret

.rotate_secret:
  image: amazon/aws-cli:2.15.0
  variables:
    SECRET_NAME: "ingest/$ENVIRONMENT_NAME/secrets"
  script:
    - |
      if [[ -z "${SECRET_NAME:-}" ]]; then
        echo "❌ ERROR: SECRET_NAME environment variable is not set."
        exit 1
      fi
      if [[ -z "${SECRET_VALUE:-}" ]]; then
        echo "❌ ERROR: SECRET_VALUE environment variable is not set."
        exit 1
      fi
      echo "Updating secret: $SECRET_NAME in aws secrets manager"
      aws secretsmanager put-secret-value \
          --secret-id "$SECRET_NAME" \
          --secret-string "$SECRET_VALUE"
      echo "✅ Secret '$SECRET_NAME' updated successfully."
  when: manual

.update_secret_in_k8s:
  image: noose/kubectl-helm-aws:1.31.0-3.16.3-2.21.0
  variables:
    SECRET_NAME: "ingest/$ENVIRONMENT_NAME/secrets"
  script:
    - |
      if [[ -z "${SECRET_NAME:-}" ]]; then
        echo "❌ ERROR: SECRET_NAME environment variable is not set."
        exit 1
      fi
      echo "Updating secret: $SECRET_NAME"
    - aws configure set profile.embl-ebi.region us-east-1
    - aws configure set profile.embl-ebi.output json
    - aws configure set profile.ebi.aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set profile.ebi.aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set profile.embl-ebi.source_profile ebi
    - aws configure set profile.embl-ebi.role_arn "arn:aws:iam::871979166454:role/ingest-devops"

    - source config/environment_$ENVIRONMENT_NAME
    - cd apps
    - set -vx
    - ./scripts/deploy_secrets
    - kubectl rollout restart deployment ingest-exporter

rotate_secret:
  stage: rotate_secret
  extends: .rotate_secret
  parallel:
    matrix:
      - ENVIRONMENT_NAME: 
        - "dev"
        # - "staging"
        # - "prod"
  environment:
    name: $ENVIRONMENT_NAME
  when: manual

update_secret_in_k8s:
  stage: rotate_secret
  extends: .update_secret_in_k8s
  parallel:
    matrix:
      - ENVIRONMENT_NAME: dev
        BRANCH_NAME: dev
      # - ENVIRONMENT_NAME: ["staging", "prod"]
        # BRANCH_NAME: master
  environment:
    name: $ENVIRONMENT_NAME
    kubernetes:
      namespace: "$ENVIRONMENT_NAME-environment"
  needs: ["rotate_secret"]
