apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingest-ingress
  annotations:
    # specifically target NGINX ingress controller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  {{- $defaultPath := .Values.ingress.ingest.defaultPath -}}
  {{- $defaultServicePort := .Values.ingress.ingest.defaultServicePort -}}
  {{ range .Values.ingress.ingest.hosts }}
  {{ $service := .service }}
    - host: {{ .hostname  }}
      http:
        paths:
          - path: {{ .path | default $defaultPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $service }}
                port:
                  number: {{ .port | default $defaultServicePort }}
  {{ end }}
