grafana:
  grafana.ini:
    server:
      domain: monitoring.ingest.integration.archive.data.humancellatlas.org
      root_url: https://monitoring.ingest.integration.archive.data.humancellatlas.org
      serve_from_sub_path: false
environment: integration-environment