FROM quay.io/humancellatlas/ingest-backup-base

RUN mkdir -p /data/db/dump

COPY src/backup.sh /opt/backup

RUN chmod +x /opt/backup

ENV S3_BUCKET=ingest-backup
ENV BACKUP_DIR=deploymentenv

ENTRYPOINT /opt/backup
