grafana:
  persistence:
    enabled: true
    type: pvc
  grafana.ini:
    smtp:
      enabled: true
      host: email-smtp.us-east-1.amazonaws.com:587
      from_address: "hca-notifications@ebi.ac.uk"
  smtp:
    existingSecret: "aws-keys"
    userKey: "notifications-smtp-username"
    passwordKey: "notifications-smtp-password"
  admin:
    existingSecret: "aws-keys"
    userKey: "grafana-admin-username"
    passwordKey: "grafana-admin-password"

  dashboards:
    default:
      ingest-monitoring:
        file: dashboards/ingest-monitoring.json