grafana:
  persistence:
    enabled: true
    type: pvc
    storageClassName: gp2
    accessModes:
    - ReadWriteOnce
    size: 4Gi
    finalizers:
    - kubernetes.io/pvc-protection
  grafana.ini:
    smtp:
      enabled: true
      host: email-smtp.us-east-1.amazonaws.com:587
      from_address: "hca-notifications@ebi.ac.uk"
  smtp:
    existingSecret: "aws-keys"
    userKey: "notifications-smtp-username"
    passwordKey: "notifications-smtp-password"
  admin:
    existingSecret: "aws-keys"
    userKey: grafana-admin-username
    passwordKey: grafana-admin-password
  defaultDashboardsEnabled: true

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      annotations: {}
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      label: grafana_datasource

  notifiers:
    notifiers.yaml:
      notifiers:
      - name: Ingest Dev Notifications
        type: slack
        uid: slack-ingest-dev
        org_id: 1
        is_default: true
        send_reminder: true
        frequency: 4h
        disable_resolve_message: false
        # See `Supported Settings` section for settings supporter for each
        # alert notification type.
        settings:
          mentionGroups: hca-ingest-dev
          username: monitoring
          uploadImage: false
          url: https://hooks.slack.com/services/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

loki:
  service:
    clusterIP: 172.20.245.170

promtail:
  config:
    lokiAddress: http://172.20.245.170:3100/loki/api/v1/push

lokiIP: 172.20.245.170
prometheusIP: localhost