# Default values for update-project-catalogue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/ebi-ait/update-project-catalogue
  tag: latest
  pullPolicy: Always
schedule: 0 22 * * *