apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/app: {{ .Values.gitlab_app }}
    app.gitlab.com/env: {{ .Values.gitlab_env }}
  labels:
    role: ingestion
  name: ingest-data-archiver
  namespace: {{ .Values.environment }}-environment
spec:
  selector:
    matchLabels:
      app: ingest-data-archiver
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-data-archiver
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        app.gitlab.com/app: {{ .Values.gitlab_app }}
        app.gitlab.com/env: {{ .Values.gitlab_env }}
    spec:
      dnsPolicy: Default
      containers:
      - env:
        - name: INGEST_API
          value: http://$(INGEST_CORE_SERVICE_SERVICE_HOST):$(INGEST_CORE_SERVICE_SERVICE_PORT)
        - name: INGEST_S3_BUCKET
          value: {{ .Values.ingestS3BucketName }}
        - name: INGEST_S3_REGION
          value: {{ .Values.ingestS3Region }}
        - name: RABBIT_HOST
          value: $(RABBIT_SERVICE_SERVICE_HOST)
        - name: RABBIT_PORT
          value: $(RABBIT_SERVICE_SERVICE_PORT_SERVICE)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: exporter-access-key-id
              name: aws-keys
        - name: AWS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: exporter-access-key-secret
              name: aws-keys
        - name: ENA_FTP_HOST
          value: {{ .Values.enaFtpHost }}
        - name: ENA_FTP_DIR
          value: {{ .Values.enaFtpDir }}
        - name: ENA_WEBIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: ena-webin-username
              name: api-keys
        - name: ENA_WEBIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ena-webin-password
              name: api-keys
        - name: ARCHIVER_DATA_DIR
          value: /data
        image: {{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-data-archiver
#        volumeMounts:
#        - mountPath: /data
#          name: archiver-data
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 40Mi
