apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/app: {{ .Values.gitlab_app }}
    app.gitlab.com/env: {{ .Values.gitlab_env }}
  labels:
    role: ingestion
  name: ingest-broker
  namespace: {{ .Values.environment }}-environment
spec:
  selector:
    matchLabels:
      app: ingest-broker
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ingest-broker
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        app.gitlab.com/app: {{ .Values.gitlab_app }}
        app.gitlab.com/env: {{ .Values.gitlab_env }}
    spec:
      dnsPolicy: Default
      volumes:
      - name: spreadsheet-storage
        persistentVolumeClaim:
          claimName: spreadsheet-storage-claim
      containers:
      - env:
        - name: INGEST_UI
          value: https://{{ .Values.ui }}
        - name: INGEST_API
          value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
        - name: SPREADSHEET_STORAGE_DIR
          value: /data/spreadsheets
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: exporter-access-key-id
              name: aws-keys
        - name: AWS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: exporter-access-key-secret
              name: aws-keys
        image: {{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-broker
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /data/spreadsheets
          name: spreadsheet-storage
        resources:
          limits:
            memory: 1.5Gi # 1536 Mib
          requests:
            memory: 400Mi
