{
 "title": "Ingest Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "containers",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"prod-environment\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster stats (changing container will not affect this)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"prod-environment\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "capacity"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prod-environment\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prod-environment\", phase=\"Succeeded\"})"
    }
   ]
  },
  { "title": "Container Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "containers" },
  {
   "title": "Logged Errors in past 24 hours",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(({container=\"$containers\", stream=~\"stderr|stdout\"} |~ \"error|ERROR\")[24h])"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time(({container=\"$containers\"} |~ \"error|ERROR\")[1m])"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"$containers\",namespace=\"prod-environment\"}"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"$containers\",namespace=\"prod-environment\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"$containers\"}"
    }
   ]
  },
  {
   "title": "Max memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{container=\"$containers\"}"
    }
   ]
  },
  { "title": "Container Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "{container=\"$containers\"} |~ \"error|ERROR\""
    }
   ]
  },
  {
   "title": "Raw Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "{container=\"$containers\"}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "ingest-core Memory Usage Alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"ingest-core\"}"
    }
   ]
  },
  {
   "title": "Pods Failed Alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "ingest-exporter Replica Count Alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"ingest-exporter\"}"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
   ]
  }
 ]
}