{
 "title": "Submission Analysis",
 "tags": [ "wip" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "submission_uuid",
    "label": "Submission UUID",
    "query": "1ab4dec0-504f-41c3-bbc0-4c0c4ef4e6fb"
   },
   { "name": "submission_id", "label": "Submission ID", "query": "669151aeeabbc6206ca55d3a" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Submission Statuses",
   "type": "logs",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{app=~\"ingest-.*\"} |= \"${submission_uuid}\" \n|= \"SubmissionStateListener\""
    }
   ]
  },
  {
   "title": "Metadata State Update",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{app=~\"ingest-.*\"} |= \"${submission_id}\" |= \"MessageHandler\""
    }
   ]
  },
  {
   "title": "Submission Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=~\"ingest-.*\"} |= \"${submission_uuid}\""
    },
    {
     "expr": "{app=~\"ingest-.*\"} |= \"${submission_id}\""
    }
   ]
  }
 ]
}