#!/bin/bash

# set up and credentials
if [ -z $AWS_ACCESS_KEY_ID ]; then echo 'Missing access key id'; exit 1; fi
if [ -z $AWS_SECRET_ACCESS_KEY ]; then echo 'Missing secret access key'; exit 1; fi

aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set profile.backup.source_profile default

alias s3backup='aws s3 --profile=backup'
