#!/usr/bin/env bash
set -a

FORCE_REFRESH=TRUE
# Versions of applications deployed. Either a branch or a tag that corresponds with an image in quay is accepted.
INGEST_NODE_ACCESSIONER_REF=627703d
INGEST_BROKER_REF=e650e6f
INGEST_CORE_REF=487b1cf
INGEST_EXPORTER_REF=5388780
INGEST_STAGING_MANAGER_REF=7791e6c
INGEST_STATE_TRACKING_REF=38a399c
INGEST_VALIDATOR_REF=a28e364
INGEST_UI_REF=b39ce5b
ONTOLOGY_REF=master

FASTQ_VALIDATOR_IMAGE=quay.io/humancellatlas/fastq_utils:v0.1.2.rc 

# REPLICAS
INGEST_BROKER_REPLICAS=1
INGEST_CORE_REPLICAS=1
INGEST_EXPORTER_REPLICAS=30
INGEST_STAGING_MANAGER_REPLICAS=30
INGEST_STATE_TRACKING_REPLICAS=1
INGEST_VALIDATOR_REPLICAS=1
INGEST_UI_REPLICAS=1

# Make sure the AWS_PROFILE below matches an aws profile in ~/.aws/config or ~/.aws/credentials with admin access to the relevant aws account.
AWS_PROFILE=hca
TF_VAR_ops_role=dcp-developer
# Make sure the vpc ip below is unique
TF_VAR_vpc_cidr_block=10.50.0.0/16

#Set values for node size and count
TF_VAR_node_size="m5.xlarge"
TF_VAR_node_count="2"




#VARIABLES BELOW SHOULD NEVER CHANGE.
FILE_NAME=$(basename $BASH_SOURCE)
DEPLOYMENT_STAGE=${FILE_NAME#*_}
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
KUBECONFIG_PATH=$PROJECT_ROOT/config/cluster-secrets/kubeconfig_${DEPLOYMENT_STAGE}
TILLER_NAMESPACE=kube-system
TF_VAR_terraform_key=ingest/eks-${DEPLOYMENT_STAGE}.tfstate
TF_VAR_aws_profile=${AWS_PROFILE}
TF_VAR_deployment_stage=${DEPLOYMENT_STAGE}
TF_VAR_account_id=$(aws sts get-caller-identity --profile ${AWS_PROFILE} | jq -r .Account)
TF_VAR_aws_region=us-east-1
TF_VAR_terraform_bucket=org-humancellatlas-${TF_VAR_account_id}-terraform

set +a

