#!/usr/bin/env bash
set -a

FORCE_REFRESH=TRUE
# Versions of applications deployed. Either a branch or a tag that corresponds with an image in quay is accepted.
INGEST_ACCESSIONER_REF=integration
INGEST_NODE_ACCESSIONER_REF=627703d
INGEST_BROKER_REF=bc6b30f
INGEST_CORE_REF=9dcfe21
INGEST_EXPORTER_REF=adb0f60
INGEST_STAGING_MANAGER_REF=40b7a9d
INGEST_STATE_TRACKING_REF=d38fd94
INGEST_VALIDATOR_REF=350fc6a
ONTOLOGY_REF=master

# Make sure the AWS_PROFILE below matches an aws profile in ~/.aws/config or ~/.aws/credentials with admin access to the relevant aws account.
AWS_PROFILE=hca
# Make sure the vpc ip below is unique
TF_VAR_vpc_cidr_block=10.50.0.0/16

#Set values for node size and count
TF_VAR_node_size="m5.xlarge"
TF_VAR_node_count="2"




#VARIABLES BELOW SHOULD NEVER CHANGE.
FILE_NAME=$(basename $BASH_SOURCE)
DEPLOYMENT_STAGE=${FILE_NAME#*_}
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
KUBECONFIG_PATH=$PROJECT_ROOT/config/cluster-secrets/kubeconfig_${DEPLOYMENT_STAGE}
TILLER_NAMESPACE=kube-system
TF_VAR_terraform_key=ingest/eks-${DEPLOYMENT_STAGE}.tfstate
TF_VAR_aws_profile=${AWS_PROFILE}
TF_VAR_deployment_stage=${DEPLOYMENT_STAGE}
TF_VAR_account_id=$(aws sts get-caller-identity --profile ${AWS_PROFILE} | jq -r .Account)
TF_VAR_aws_region=us-east-1
TF_VAR_terraform_bucket=org-humancellatlas-${TF_VAR_account_id}-terraform

set +a

