#!/usr/bin/env zsh
set -a

# Make a copy of this file in this directory and replace the variables with stub 'PROVIDE...' values

FORCE_REFRESH=TRUE
# Versions of applications deployed. Either a branch or a tag that corresponds with an image in quay is accepted.
ONTOLOGY_REF=PROVIDE_IMAGE_OR_BRANCH_NAME

# Make sure the AWS_PROFILE below matches an aws profile in ~/.aws/config or ~/.aws/credentials with admin access to the relevant aws account.
AWS_PROFILE=PROVIDE_YOUR_OWN_VALUE
TF_VAR_ops_role=PROVIDE_YOUR_OWN_VALUE
# Make sure the vpc ip below is unique
TF_VAR_vpc_cidr_block=PROVIDE_UNIQUE_VPC_IP_VALUE

#Set values for node size and count
TF_VAR_node_size="m5.xlarge"
TF_VAR_node_count="2"





#VARIABLES BELOW SHOULD NEVER CHANGE.
SOURCE_FILE=${(%):-%x}
FILE_NAME=${SOURCE_FILE:t}
DEPLOYMENT_STAGE=${FILE_NAME#*_}
PROJECT_ROOT="$( cd "$( dirname "${SOURCE_FILE}" )"/.. && pwd )"
KUBECONFIG_PATH=$PROJECT_ROOT/config/cluster-secrets/kubeconfig_${DEPLOYMENT_STAGE}
TF_VAR_terraform_key=ingest/eks-${DEPLOYMENT_STAGE}.tfstate
TF_VAR_aws_profile=${AWS_PROFILE}
TF_VAR_deployment_stage=${DEPLOYMENT_STAGE}
TF_VAR_account_id=$(aws sts get-caller-identity --profile ${AWS_PROFILE} | jq -r .Account)
TF_VAR_aws_region=us-east-1
TF_VAR_terraform_bucket=org-humancellatlas-${TF_VAR_account_id}-terraform

source $PROJECT_ROOT/config/replicas/environment_${DEPLOYMENT_STAGE}

set +a
