#!/usr/bin/env bash
set -a

FORCE_REFRESH=TRUE
# Versions of applications deployed. Either a branch or a tag that corresponds with an image in quay is accepted.
INGEST_ACCESSIONER_REF=v0.4.0.rc
INGEST_NODE_ACCESSIONER_REF=v0.5.0.rc
INGEST_BROKER_REF=37e15b8
INGEST_CORE_REF=v0.8.2.rc
INGEST_EXPORTER_REF=v0.7.7.rc
INGEST_STAGING_MANAGER_REF=v0.5.3.rc
INGEST_STATE_TRACKING_REF=v0.7.4.rc
INGEST_VALIDATOR_REF=v0.6.0.rc
ONTOLOGY_REF=master

FASTQ_VALIDATOR_IMAGE=quay.io/humancellatlas/fastq_utils:v0.1.0.rc 

# Make sure the AWS_PROFILE below matches an aws profile in ~/.aws/config or ~/.aws/credentials with admin access to the relevant aws account.
AWS_PROFILE=hca
# Make sure the vpc ip below is unique
TF_VAR_vpc_cidr_block=10.60.0.0/16

#Set values for node size and count
TF_VAR_node_size="m5.xlarge"
TF_VAR_node_count="2"





#VARIABLES BELOW SHOULD NEVER CHANGE.
FILE_NAME=$(basename $BASH_SOURCE)
DEPLOYMENT_STAGE=${FILE_NAME#*_}
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
KUBECONFIG_PATH=$PROJECT_ROOT/config/cluster-secrets/kubeconfig_${DEPLOYMENT_STAGE}
TILLER_NAMESPACE=kube-system
TF_VAR_terraform_key=ingest/eks-${DEPLOYMENT_STAGE}.tfstate
TF_VAR_aws_profile=${AWS_PROFILE}
TF_VAR_deployment_stage=${DEPLOYMENT_STAGE}
TF_VAR_account_id=$(aws sts get-caller-identity --profile ${AWS_PROFILE} | jq -r .Account)
TF_VAR_aws_region=us-east-1
TF_VAR_terraform_bucket=org-humancellatlas-${TF_VAR_account_id}-terraform

set +a
