#!/usr/bin/env bash
set -a

FORCE_REFRESH=TRUE
# Versions of applications deployed. Either a branch or a tag that corresponds with an image in quay is accepted.
INGEST_ACCESSIONER_REF=integration
INGEST_BROKER_REF=integration
INGEST_CORE_REF=integration
INGEST_EXPORTER_REF=integration
INGEST_STAGING_MANAGER_REF=integration-18.06.29
INGEST_STATE_TRACKING_REF=integration
INGEST_VALIDATOR_REF=integration
ONTOLOGY_REF=master

# Make sure the AWS_PROFILE below matches an aws profile in ~/.aws/config or ~/.aws/credentials with admin access to the relevant aws account.
AWS_PROFILE=hca
# Make sure the vpc ip below is unique
TF_VAR_vpc_cidr_block=10.50.0.0/16





#VARIABLES BELOW SHOULD NEVER CHANGE.
FILE_NAME=$(basename $BASH_SOURCE)
DEPLOYMENT_STAGE=${FILE_NAME#*_}
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
KUBECONFIG_PATH=$PROJECT_ROOT/config/cluster-secrets/kubeconfig_${DEPLOYMENT_STAGE}
TILLER_NAMESPACE=kube-system
TF_VAR_terraform_key=ingest/eks-${DEPLOYMENT_STAGE}.tfstate
TF_VAR_aws_profile=${AWS_PROFILE}
TF_VAR_deployment_stage=${DEPLOYMENT_STAGE}
TF_VAR_account_id=$(aws sts get-caller-identity --profile ${AWS_PROFILE} | jq -r .Account)
TF_VAR_aws_region=us-east-1
TF_VAR_terraform_bucket=org-humancellatlas-${TF_VAR_account_id}-terraform

set +a

