apiVersion: v1
data:
  aap-api-password: {{ .Values.apiKeys.aapApiPassword }}
  archiver-api-key: {{ .Values.apiKeys.archiverApiKey }}
  staging-api-key: {{ .Values.apiKeys.stagingApiKey }}
  exporter-terra-auth-info: {{ .Values.apiKeys.exporterTerraAuthInfo }}
kind: Secret
metadata:
  annotations: {}
  name: api-keys
  namespace: {{ .Values.environment }}-environment
type: Opaque
---
apiVersion: v1
data:
  aws-access-key-id: {{ .Values.awsKeys.accessKeyId }}
  aws-secret-access-key: {{ .Values.awsKeys.secretAccessKey }}
  exporter-access-key-id: {{ .Values.awsKeys.exporterAccessKeyId }}
  exporter-access-key-secret: {{ .Values.awsKeys.exporterAccessKeySecret }}
  notifications-smtp-username: {{ .Values.awsKeys.notificationsSmtpUsername }}
  notifications-smtp-password: {{ .Values.awsKeys.notificationsSmtpPassword }}
stringData:
  grafana-admin-username: {{ .Values.awsKeys.grafanaAdminUsername }}
  grafana-admin-password: {{ .Values.awsKeys.grafanaAdminPassword }}
kind: Secret
metadata:
  annotations: {}
  name: aws-keys
  namespace: {{ .Values.environment }}-environment
type: Opaque
