apiVersion: v1
data:
  aap-api-password: {{ .Values.apiKeys.aapApiPassword }}
  staging-api-key: {{ .Values.apiKeys.stagingApiKey }}
  exporter-auth-info: {{ .Values.apiKeys.exporterAuthInfo }}
  exporter-terra-auth-info: {{ .Values.apiKeys.exporterTerraAuthInfo }}
kind: Secret
metadata:
  annotations: {}
  name: api-keys
  namespace: {{ .Values.environment }}-environment
type: Opaque
---
apiVersion: v1
data:
  aws-access-key-id: {{ .Values.awsKeys.accessKeyId }}
  aws-secret-access-key: {{ .Values.awsKeys.secretAccessKey }}
  exporter-access-key-id: {{ .Values.awsKeys.exporterAccessKeyId }}
  exporter-access-key-secret: {{ .Values.awsKeys.exporterAccessKeySecret }}
kind: Secret
metadata:
  annotations: {}
  name: aws-keys
  namespace: {{ .Values.environment }}-environment
type: Opaque
