apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations: {}
  name: api-keys
  namespace: {{ .Values.environment }}-environment
data:
  aap-api-password: {{ .Values.apiKeys.aapApiPassword | quote }}
  archiver-api-key: {{ .Values.apiKeys.archiverApiKey | quote }}
  staging-api-key: {{ .Values.apiKeys.stagingApiKey | quote }}
  exporter-terra-auth-info: {{ .Values.apiKeys.exporterTerraAuthInfo | quote }}
  ingest-service-account-auth-info: {{ .Values.apiKeys.ingestServiceAccountAuthInfo | quote }}
  biostudies-api-username: {{ .Values.apiKeys.biostudiesApiUsername | quote }}
  biostudies-api-password: {{ .Values.apiKeys.biostudiesApiPassword | quote }}
  ena-webin-username: {{ .Values.apiKeys.enaWebinUsername | quote }}
  ena-webin-password: {{ .Values.apiKeys.enaWebinPassword | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations: {}
  name: aws-keys
  namespace: {{ .Values.environment }}-environment
data:
  aws-access-key-id: {{ .Values.awsKeys.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.awsKeys.secretAccessKey | quote }}
  exporter-access-key-id: {{ .Values.awsKeys.exporterAccessKeyId | quote }}
  exporter-access-key-secret: {{ .Values.awsKeys.exporterAccessKeySecret | quote }}
  notifications-smtp-username: {{ .Values.awsKeys.notificationsSmtpUsername | quote }}
  notifications-smtp-password: {{ .Values.awsKeys.notificationsSmtpPassword | quote }}
  runner-registration-token: {{ .Values.awsKeys.gitlabGroupRunnerToken | quote }}
  runner-token: ""
stringData:
  grafana-admin-username: {{ .Values.awsKeys.grafanaAdminUsername | quote }}
  grafana-admin-password: {{ .Values.awsKeys.grafanaAdminPassword | quote }}
