vpa:
  recommender:
    extraArgs:
      prometheus-address: http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local 
      storage: prometheus
  admissionController:
    enabled: true

goldilocks:
  dashboard:
    replicaCount: 1
  