apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: ingest-ontology-service
  name: ingest-ontology-service
  namespace: staging-environment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingest-ontology
  sessionAffinity: None
  type: LoadBalancer
