apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-archiver
  namespace: {{ .Values.environment }}-environment
spec:
  selector:
    matchLabels:
      app: ingest-archiver
  replicas: 1
  template:
    metadata:
      labels:
        app: ingest-archiver
    spec:
      dnsPolicy: Default
      containers:
      - env:
        - name: RABBITMQ_URL
          value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        - name: INGEST_API_URL
          value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
        - name: ONTOLOGY_API_URL
          value: http://${ONTOLOGY_SERVICE_SERVICE_HOST}:${ONTOLOGY_SERVICE_SERVICE_PORT}
        - name: DSP_API_URL
          value: https://{{ .Values.dspUrl }}
        - name: AAP_API_URL
          value: https://{{ .Values.aapUrl }}
        - name: AAP_API_DOMAIN
          value: https://{{ .Values.aapDomain }}
        - name: AAP_API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: aap-api-password
              name: api-keys
        - name: AAP_API_USER
          value: https://{{ .Values.aapUser }}
        image: quay.io/ebi-ait/ingest-archiver:{{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-archiver
        ports:
        - containerPort: 5000