apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: dev-environment
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gitlab-ci
  name: gitlab-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-admin
  namespace: gitlab-ci
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: dev-environment
roleRef:
  kind: Role
  name: gitlab-admin
  apiGroup: rbac.authorization.k8s.io