uploadScheme: https
uploadPort: 443
upload: upload.dev.archive.data.humancellatlas.org
dss: dss.dev.data.humancellatlas.org
schema: schema.staging.data.humancellatlas.org
ingest: api.ingest.dev.archive.data.humancellatlas.org
broker: ingest.dev.archive.data.humancellatlas.org
ui: dev.contribute.data.humancellatlas.org

# config values
gcpProjectWhitelist: "ingest-service-301110.iam.gserviceaccount.com"
svcAuthAudience: https://dev.data.humancellatlas.org/
usrAuthAudience: https://dev.data.humancellatlas.org/

# ui
domainWhitelist: "api.ingest.dev.archive.data.humancellatlas.org,ingest.dev.archive.data.humancellatlas.org"
securedEndpoints: '\/auth\/.*,\/user\/.*,\/submissionEnvelopes\/?.*,\/projects$'
aaiClientId: "e2041c2d-9449-4468-856e-e84711cebd21"
aaiAuthority: "https://login.elixir-czech.org/oidc/"

olsUrl: "https://www.ebi.ac.uk/ols4"

# exporter
terraBucketName: broad-dsp-monster-hca-dev-ebi-staging
terraBucketPrefix: dev
terraGcpProject: broad-dsp-monster-hca-dev
gcsNotificationTopic: broad-dsp-monster-hca-dev.staging-transfer-notifications.ebi
gcsNotificationSub: ebi-writer

# core
debug: false
notifications:
  smtp:
    host: email-smtp.us-east-1.amazonaws.com
    port: "587"
    wranglerEmails: hca-notifications-test@ebi.ac.uk
    projectNotificationsFromAddress: hca-notifications-test@ebi.ac.uk
  amqp:
    sendExchange: ingest.notifications.exchange
    sendRoutingKey: ingest.notifications.new

# archiver
dspUrl: https://submission-test.ebi.ac.uk
aapUrl: https://explore.api.aai.ebi.ac.uk/auth
aapUser: hca-ingest
aapDomain: subs.test-team-21
biostudiesApiUrl: https://wwwdev.ebi.ac.uk/biostudies/submissions/api
biostudiesStudyUrl: https://wwwdev.ebi.ac.uk/biostudies/studies/
enaWebinApiUrl: https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/
enaFtpHost: webin.ebi.ac.uk
enaFtpDir: dev

# validator
fastqImage: quay.io/ebi-ait/fastq_utils:54bcf9f

# s3 bucket
ingestS3Region: us-east-1
ingestS3BucketName: org-hca-data-archive-upload-dev
