uploadScheme: https
uploadPort: 443
upload: upload.dev.archive.data.humancellatlas.org
dss: dss.dev.data.humancellatlas.org
schema: schema.dev.data.humancellatlas.org
ingest: api.ingest.dev.archive.data.humancellatlas.org
broker: ingest.dev.archive.data.humancellatlas.org
ui: ui.ingest.dev.archive.data.humancellatlas.org

# config values
gcpProjectWhitelist: "hca-dcp-production.iam.gserviceaccount.com,human-cell-atlas-travis-test.iam.gserviceaccount.com,broad-dsde-mint-dev.iam.gserviceaccount.com,broad-dsde-mint-test.iam.gserviceaccount.com,broad-dsde-mint-staging.iam.gserviceaccount.com"
svcAuthAudience: https://dev.data.humancellatlas.org/
usrAuthAudience: https://dev.data.humancellatlas.org/

# ui
domainWhitelist: "api.ingest.dev.archive.data.humancellatlas.org,ingest.dev.archive.data.humancellatlas.org"
aaiClientId: "e2041c2d-9449-4468-856e-e84711cebd21"
aaiAuthority: "https://login.elixir-czech.org/oidc/"

olsUrl: "https://ontology.dev.archive.data.humancellatlas.org"
