uploadScheme: https
uploadPort: 443
upload: upload.archive.data.humancellatlas.org
dss: dss.data.humancellatlas.org
schema: schema.humancellatlas.org
ingest: api.ingest.archive.data.humancellatlas.org
broker: ingest.archive.data.humancellatlas.org
ui: contribute.data.humancellatlas.org

# config values
gcpProjectWhitelist: "ingest-service-301110.iam.gserviceaccount.com"
svcAuthAudience: https://data.humancellatlas.org/
usrAuthAudience: https://dev.data.humancellatlas.org/

# ui
domainWhitelist: "api.ingest.archive.data.humancellatlas.org,ingest.archive.data.humancellatlas.org"
securedEndpoints: '\/auth\/.*,\/user\/.*,\/submissionEnvelopes$,\/projects$'
authDomain: "auth.data.humancellatlas.org"
aaiClientId: "e2041c2d-9449-4468-856e-e84711cebd21"
aaiAuthority: "https://login.elixir-czech.org/oidc/"

olsUrl: "https://ontology.archive.data.humancellatlas.org"

# exporter
terraBucketName: broad-dsp-monster-hca-prod-ebi-storage
terraBucketPrefix: prod
terraGcpProject: mystical-slate-284720
gcsNotificationTopic: broad-dsp-monster-hca.staging-transfer-notifications.ebi
gcsNotificationSub: ebi-writer

# core
debug: false
notifications:
  smtp:
    host: email-smtp.us-east-1.amazonaws.com
    port: "587"
    wranglerEmails: hca-notifications@ebi.ac.uk
    projectNotificationsFromAddress: hca-notifications@ebi.ac.uk
  amqp:
    sendExchange: ingest.notifications.exchange
    sendRoutingKey: ingest.notifications.new

# archiver
dspUrl: https://submission.ebi.ac.uk
aapUrl: https://api.aai.ebi.ac.uk/auth
aapUser: hca-ingest
aapDomain: subs.team-2
biostudiesApiUrl: https://www.ebi.ac.uk/biostudies/submissions/api
biostudiesStudyUrl: https://www.ebi.ac.uk/biostudies/studies/
enaWebinApiUrl: https://www.ebi.ac.uk/ena/submit/drop-box/submit/
enaFtpHost: webin.ebi.ac.uk
enaFtpDir: prod

# validator
fastqImage: quay.io/ebi-ait/fastq_utils:d2020-09-07.1
