uploadScheme: https
uploadPort: 443
upload: upload.archive.data.humancellatlas.org
dss: dss.data.humancellatlas.org
schema: schema.humancellatlas.org
ingest: api.ingest.archive.data.humancellatlas.org
broker: ingest.archive.data.humancellatlas.org
ui: ui.ingest.archive.data.humancellatlas.org

# config values
gcpProjectWhitelist: "hca-dcp-pipelines-prod.iam.gserviceaccount.com,hca-dcp-production.iam.gserviceaccount.com"
svcAuthAudience: https://data.humancellatlas.org/
usrAuthAudience: https://dev.data.humancellatlas.org/

# ui
domainWhitelist: "api.ingest.archive.data.humancellatlas.org,ingest.archive.data.humancellatlas.org"
authDomain: "auth.data.humancellatlas.org"
aaiClientId: "e2041c2d-9449-4468-856e-e84711cebd21"
aaiAuthority: "https://login.elixir-czech.org/oidc/"

olsUrl: "https://ontology.archive.data.humancellatlas.org"

# archiver
dspUrl: https://submission.ebi.ac.uk
aapUrl: https://api.aai.ebi.ac.uk/auth
aapUser: hca-ingest
aapDomain: subs.team-2
