apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ontology
  namespace: {{ .Values.environment }}-environment
spec:
  selector:
    matchLabels:
      app: ontology
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ontology
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - image: quay.io/ebi-ait/ontology:{{ .Values.image }}
        imagePullPolicy: Always
        name: ontology
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2.5Gi #2560 Mib
          requests:
            memory: 1.8Gi # 1843 Mib
