apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ontology
  namespace: {{ .Values.environment }}-environment
spec:
  selector:
    matchLabels:
      app: ontology
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ontology
    spec:
      containers:
      - image: quay.io/humancellatlas/ontology:{{ .Values.image }}
        imagePullPolicy: Always
        name: ontology
        ports:
        - containerPort: 8080
