apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ingest-backup
spec:
  schedule: {{ .Values.cronSchedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup-keys
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-keys
                  key: aws-secret-access-key
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket }}
            - name: BACKUP_DIR
              value: {{ .Values.s3.directory }}
          restartPolicy: OnFailure
