ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.dev.archive.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.dev.archive.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.dev.archive.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: dev.contribute.data.humancellatlas.org
      - service: ingest-archiver-service
        hostname: archiver.ingest.dev.archive.data.humancellatlas.org
      - service: ingest-monitoring-grafana
        hostname: monitoring.ingest.dev.archive.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:871979166454:certificate/639a8e4c-46eb-4c4b-932e-2b581a97218c

