ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.dev.archive.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.dev.archive.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.dev.archive.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: ui.dev.archive.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:871979166454:certificate/84699165-b161-4b3f-b2c3-5c8c23d397e6

