ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.integration.archive.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.integration.archive.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.integration.archive.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: integration.contribute.data.humancellatlas.org
      - service: ingest-archiver-service
        hostname: archiver.ingest.integration.archive.data.humancellatlas.org

ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: Local
      omitClusterIP: true
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:871979166454:certificate/25df76e7-578f-42ca-9d2f-765be81e9ded
