ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-ui-service
        hostname: integration.contribute.data.humancellatlas.org
      - service: ingest-monitoring-grafana
        hostname: monitoring.ingest.integration.archive.data.humancellatlas.org

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:871979166454:certificate/307fff35-9111-4df2-9945-2333dc5d26d2
