ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.archive.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.archive.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.archive.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: ui.ingest.archive.data.humancellatlas.org
      - service: ingest-archiver-service
        hostname: archiver.ingest.archive.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:871979166454:certificate/ec6c3fb9-d4f2-41c6-a3c2-15447ed1a249
