ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.archive.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.archive.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.archive.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: contribute.data.humancellatlas.org
      - service: ingest-archiver-service
        hostname: archiver.ingest.archive.data.humancellatlas.org
      - service: ingest-monitoring-grafana
        hostname: monitoring.ingest.archive.data.humancellatlas.org

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:871979166454:certificate/3465ac2b-b7e5-475b-9ab5-3bc72fb98b84
