ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.staging.archive.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.staging.archive.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.staging.archive.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: staging.contribute.data.humancellatlas.org
      - service: ingest-archiver-service
        hostname: archiver.ingest.staging.archive.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:871979166454:certificate/5a03d751-d116-4480-8a05-1d7767862c58
