ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.testing.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.testing.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.testing.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: ui.ingest.testing.data.humancellatlas.org

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:861229788715:certificate/86982ec7-62da-4b70-a467-159386f0130f
