apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasources
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local 
        access: proxy
        isDefault: false
        editable: true
      - name: Loki
        type: loki
        url: http://{{ .Release.Name }}-loki.{{ .Release.Namespace }}.svc.cluster.local:3100
        isDefault: true
        editable: true