apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-datasources
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://localhost:80
        access: proxy
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        url: http://localhost:3100
        isDefault: false
        editable: true