apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: neo4j
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  serviceName: neo4j-service
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - image: neo4j:3.5.14-enterprise
        name: neo4j
        ports:
          - name: tcp-http
            containerPort: 7474
          - name: tcp-bolt
            containerPort: 7687
        env:
          - name: NEO4J_AUTH
            value: "neo4j/password"
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
        resources:
          requests:
            memory: 2.8Gi