apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: submission
  name: rabbit-service
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
  - name: service
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: manager
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbit
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
